behnam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('catalog/', include('catalog.urls')),
    path('', include('content.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls')),
    path('project/', include('project.urls')),

]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

blog/urls.py
from django.urls import path

from blog.views import SinglePost, PostList, categoryList, tagList, Author, SearchBlog

app_name = 'blog'
urlpatterns = [
    path("search/", SearchBlog.as_view(), name="search"),
    path('<slug>', SinglePost, name='SinglePost'),
    path('', PostList.as_view(), name='PostList'),
    path('category/<slug>', categoryList.as_view(), name='categoryList'),
    path('tag/<slug>', tagList.as_view(), name='tagList'),
    path('author/<slug:username>', Author.as_view(), name='Author'),
]

catalog/urls.py
from django.urls import path

from catalog.views import CatalogList

app_name = 'catalog'
urlpatterns = [
    path('', CatalogList.as_view(), name='List'),
]

content/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from content.sitemap import BlogSitemap, ProjectSitemap, ProductSitemap, StaticViewSitemap, BCSitemap, BTSitemap, \
    PCSitemap, PTSitemap, ProductCSitemap, ProductTSitemap
from content.views import about, contactus, home

app_name = 'content'
sitemaps = {
    'blog': BlogSitemap,
    'project': ProjectSitemap,
    'product': ProductSitemap,
    'url': StaticViewSitemap,
    'BCSitemap': BCSitemap,
    'BTSitemap': BTSitemap,
    'PCSitemap': PCSitemap,
    'PTSitemap': PTSitemap,
    'ProductCSitemap': ProductCSitemap,
    'ProductTSitemap': ProductTSitemap,
}

urlpatterns = [
    path('about/', about, name='about'),
    path('contactus/', contactus, name='contactus'),
    path('', home, name='index'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

product/urls.py
from django.urls import path

from product.views import product, ProductList, ProductCategoryList, ProductTagList, SearchProduct

app_name = 'product'
urlpatterns = [
    path('category/<slug>', ProductCategoryList.as_view(), name='categoryList'),
    path("search/", SearchProduct.as_view(), name="search"),
    path('<slug>', product, name='product'),
    path('', ProductList.as_view(), name='ProductList'),
    path('tag/<slug>', ProductTagList.as_view(), name='tagList'),
]

project/urls.py
from django.urls import path

from project.views import single_project, ProjectList, ProjectTagList, ProjectCategoryList, SearchProject

app_name = 'project'
urlpatterns = [
    path('category/<slug>', ProjectCategoryList.as_view(), name='CategoryList'),
    path("search/", SearchProject.as_view(), name="search"),
    path('<slug>', single_project, name='Project'),
    path('', ProjectList.as_view(), name='ProjectList'),
    path('tag/<slug>', ProjectTagList.as_view(), name='tagList'),
]

content/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.utils.html import format_html
from account.models import User


class About(models.Model):
    our_team = models.ManyToManyField(User, verbose_name='تیم ما', related_name='ourTeam')
    image = models.ImageField(null=True, blank=True, verbose_name='تصویر')
    body = RichTextUploadingField(verbose_name='متن درباره ما', null=True)
    description = models.CharField(max_length=300, null=True, blank=True, verbose_name='متای توضیحات')
    keyword = models.CharField(max_length=300, verbose_name='کلمات کلیدی', null=True, blank=True)
    social_media = models.ManyToManyField('SocialMedia', verbose_name='شبکه های اجتماعی', related_name='SocialMedia')
    admin_message = models.CharField(max_length=900, verbose_name='پیام مدیر', null=True)
    history = models.IntegerField(verbose_name='سابقه کاری', null=True)

    class Meta:
        verbose_name = 'درباره ما'
        verbose_name_plural = 'درباره ما'


class SocialMedia(models.Model):
    title = models.CharField(max_length=50, verbose_name='عنوان')
    link = models.CharField(max_length=300, verbose_name='لینک')
    image = models.FileField(upload_to='social/', verbose_name='آیکون شبکه اجتماعی')

    class Meta:
        verbose_name = 'شبکه اجتماعی'
        verbose_name_plural = 'شبکه های اجتماعی'

    def __str__(self):
        return self.title

    def thumb(self):
        return format_html("<img width=90 style='border-radius: 5px' src='{}'>".format(self.image.url))

    thumb.short_description = "تصویر"


class ContactUs(models.Model):
    choice = (
        ('پشتیبانی سایت', 'پشتیبانی سایت'),
        ('انتقادات و پیشنهادات', 'انتقادات و پیشنهادات'),
        ('پیگیری سفارش', 'پیگیری سفارش'),
        ('پشتیبانی محصول', 'پشتیبانی محصول'),
        ('مدیریت', 'مدیریت'),
        ('حسابداری و امورمالی ', 'حسابداری و امورمالی'),
        ('سایر موضوعات', 'سایر موضوعات'),
    )
    subject = models.CharField(max_length=50, null=True, choices=choice, verbose_name='موضوع')
    name = models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')
    email = models.EmailField(verbose_name='ایمیل')
    phone = models.CharField(max_length=11, verbose_name='تلفن تماس')
    message = models.TextField(verbose_name='متن پیام')
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')
    is_read = models.BooleanField(default=False, verbose_name="خوانده شده")

    class Meta:
        verbose_name = 'تماس با ما'
        verbose_name_plural = 'تماس با ما'

    def __str__(self):
        return self.subject


class SiteSetting(models.Model):
    image = models.FileField(upload_to='site_setting/', verbose_name='عکس')
    title = models.CharField(max_length=50, verbose_name='عنوان', null=True)

    class Meta:
        verbose_name = 'تنظیمات سایت'
        verbose_name_plural = 'تنظیمات سایت'

    def __str__(self):
        return self.title

    def thumb(self):
        return format_html("<img width=90 style='border-radius: 5px' src='{}'>".format(self.image.url))

    thumb.short_description = "تصویر"


class Communication(models.Model):
    email = models.EmailField(verbose_name='ایمیل')
    phone = models.CharField(max_length=11, verbose_name='همراه')
    tel = models.CharField(max_length=11, verbose_name='تلفن تماس')
    fax = models.CharField(max_length=11, verbose_name='فکس', null=True)
    staff = models.CharField(max_length=11, verbose_name='کارشناس', null=True)
    staff1 = models.CharField(max_length=11, verbose_name='کارشناس', null=True)
    address = models.CharField(max_length=100, verbose_name='آدرس دفتر')
    address1 = models.CharField(max_length=100, null=True, verbose_name='آدرس کارخانه')

    class Meta:
        verbose_name = 'ارتباط'
        verbose_name_plural = 'ارتباطات'

    def __str__(self):
        return self.email


class Slider(models.Model):
    image = models.FileField(upload_to='slider/', verbose_name='عکس')
    title = models.CharField(max_length=50, verbose_name='عنوان', null=True)
    link = models.CharField(max_length=300, verbose_name='لینک')

    class Meta:
        verbose_name = 'اسلاید'
        verbose_name_plural = 'اسلاید'

    def __str__(self):
        return self.title

    def thumb(self):
        return format_html("<img width=90 style='border-radius: 5px' src='{}'>".format(self.image.url))

    thumb.short_description = "تصویر"


class Licence(models.Model):
    image = models.FileField(upload_to='slider/', verbose_name='عکس')
    title = models.CharField(max_length=50, verbose_name='عنوان', null=True)

    class Meta:
        verbose_name = 'مجوز'
        verbose_name_plural = 'مجوزها'

    def __str__(self):
        return self.title

    def thumb(self):
        return format_html("<img width=90 style='border-radius: 5px' src='{}'>".format(self.image.url))

    thumb.short_description = "تصویر"


class First(models.Model):
    image = models.FileField(upload_to='first/', verbose_name='عکس')
    body = RichTextUploadingField(verbose_name='متن درباره ما')

    class Meta:
        verbose_name = 'بخش زیر اسلایدر'
        verbose_name_plural = 'بخش زیر اسلایدر'

    def thumb(self):
        return format_html("<img width=90 style='border-radius: 5px' src='{}'>".format(self.image.url))

    thumb.short_description = "تصویر"


class Why(models.Model):
    title = models.CharField(max_length=50, verbose_name='عنوان')
    image = models.FileField(upload_to='why/', verbose_name='عکس')
    body = models.CharField(max_length=200, verbose_name=' توضیحات')
    installer = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'چرا تورک پارکر'
        verbose_name_plural = 'چرا تورک پارکر'

    def __str__(self):
        return self.title

    def thumb(self):
        return format_html("<img width=90 style='border-radius: 5px' src='{}'>".format(self.image.url))

    thumb.short_description = "تصویر"

content/forms.py
from django import forms
from django.core import validators

choice = (
    ('پشتیبانی سایت', 'پشتیبانی سایت'),
    ('انتقادات و پیشنهادات', 'انتقادات و پیشنهادات'),
    ('پیگیری سفارش', 'پیگیری سفارش'),
    ('پشتیبانی محصول', 'پشتیبانی محصول'),
    ('مدیریت', 'مدیریت'),
    ('حسابداری و امورمالی ', 'حسابداری و امورمالی'),
    ('سایر موضوعات', 'سایر موضوعات'),
)


class ContactUsForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': "form-control form-control-solid"}),
        label='نام و نام خانوادگی',
        required=True,
        validators=[validators.MaxLengthValidator(150, 'حداکثر 150 کارکتر')]
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': "form-control form-control-solid"}),
        label='ایمیل',
        required=True

    )
    subject = forms.ChoiceField(
        widget=forms.Select(attrs={'class': "form-control form-control-solid select2-selection select2-selection--single form-select "}),
        label='موضوع',
        choices=choice,
        initial='',
        required=True
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={'class': "form-control form-control-solid"}),
        label='متن پیام',
        required=True
    )
    phone = forms.CharField(
        widget=forms.TextInput(attrs={'class': "form-control form-control-solid"}),
        label='تلفن تماس',
        required=True,
        validators=[validators.MaxLengthValidator(11, 'حداکثر 11 کارکتر'), validators.MinLengthValidator(11, 'حداقل '
                                                                                                             '11 '
                                                                                                             'کارکتر')],
    )

content/views.py
from django.shortcuts import render, redirect

from blog.models import Blog
from content.forms import ContactUsForm
from content.models import About, ContactUs, Communication, Slider, First, Why
from costumer.models import Costumer
from product.models import ProductCategory, Product
from project.models import Project


def about(request):
    about_ = About.objects.first()
    communicate = Communication.objects.all().first()
    costumer_ = Costumer.objects.count()
    project_ = Project.objects.count()
    context = {
        'object': about_,
        'com': communicate,
        'costumer': costumer_,
        'project': project_,
    }
    return render(request, 'about.html', context)


def contactus(request):
    communicate = Communication.objects.all().first()
    about_ = About.objects.all().first()

    if request.method == 'POST':
        contact_form = ContactUsForm(request.POST or None)
        if contact_form.is_valid():
            name = contact_form.cleaned_data.get('name')
            email = contact_form.cleaned_data.get('email')
            subject = contact_form.cleaned_data.get('subject')
            message = contact_form.cleaned_data.get('message')
            phone = contact_form.cleaned_data.get('phone')
            ContactUs.objects.create(name=name, email=email, subject=subject, message=message, phone=phone,
                                     is_read=False)
            return redirect('content:contactus')
    else:
        contact_form = ContactUsForm()
    context = {
        'contact_form': contact_form,
        'com': communicate,
        'object': about_,
    }
    return render(request, 'contact us.html', context)


def home(request):
    blog = Blog.objects.filter(status='p')
    prd = Product.objects.filter(status='p')
    proj = Project.objects.filter(status='p')
    why = Why.objects.all()
    context = {
        'slide': Slider.objects.all(),
        'why': why,
        'category': ProductCategory.objects.filter(status='p', subClass=None),
        'project': proj.first(),
        'project_': proj[1:5],
        'product_': prd.first(),
        'product': prd[1:5],
        'blog': blog.first(),
        'blog_': blog[1:5],
    }
    return render(request, 'index.html', context)

content/templates/partial/MenuBlog.html
{% for a in object %}
    <li class="{% if a.Child.count != 0 %} submenu {% endif %}sport first"><a
            href="{% url 'blog:categoryList' a.slug %}"
            class="submenu sport first"
            aria-haspopup="true" itemprop="url"><span
            itemprop="name">{{ a.title }}</span></a>
        <div class="submenu level_3 ps-20">
            <ul class="level_3">
                {% for b in a.Child.all %}
                    <li class="sport first"><a
                            href="{% url 'blog:categoryList' b.slug %}"
                            class="sport first" itemprop="url"><span itemprop="name">{{ b.title }}</span></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </li>
{% endfor %}

content/templates/partial/com.html
<div class="w-250px">
    <div class="row  ">
        <div class="col-6 ">
                <i class="las la-mobile-alt ms-5   text-success fs-2x"></i><a href="tel:{{ com.phone }}">{{ com.phone }}</a>

        </div>
        <div class="col-6 ">
                    <i class="las la-tty text-success ms-5  fs-2x"></i><a href="tel:{{ com.tel }}">{{ com.tel }}</a>

        </div>

</div>

</div>

content/templates/partial/footer.html
<div class="inside">

    <div class="right pe-5">
        <div class="inner-row top-row">
            <div class="logo-wrapper" dir="rtl">
                <a href="/">
                    <img src="{{ logo.image.url }}" alt="{{ logo.title }}">
                </a>
            </div>
            <div class="contact-info " dir="ltr">
                <a href="tel:{{ com.phone }}" class="tel">
                        <span>
                            <svg id="phone-icon"
                                 xmlns="http://www.w3.org/2000/svg" width="33.646"
                                 height="33.708" viewBox="0 0 33.646 33.708">
                                        <g id="Ebene_2" data-name="Ebene 2" transform="translate(0 0.011)">
                                            <g id="Ebene_1" data-name="Ebene 1">
                                                <path id="Path_1576" data-name="Path 1576"
                                                      d="M14,6.88,9.32,1.08A2.89,2.89,0,0,0,5,.85L1.64,4.22A5.63,5.63,0,0,0,.75,11l.83,1.43A52.14,52.14,0,0,0,21.31,31.89L23.36,33A5.66,5.66,0,0,0,30,32.12l2.78-2.74a2.92,2.92,0,0,0,.86-2.26A3,3,0,0,0,32.53,25l-6.94-5.26a2.9,2.9,0,0,0-2.46-.5l-2.74.68a1.11,1.11,0,0,1-1-.23l-5-4.26a1.08,1.08,0,0,1-.38-1l.65-5.38A2.94,2.94,0,0,0,14,6.88Zm4.21,14.17a2.88,2.88,0,0,0,2.58.61L23.57,21a1.08,1.08,0,0,1,.93.2l6.94,5.26a1.1,1.1,0,0,1,.11,1.67l-2.77,2.74a3.85,3.85,0,0,1-4.55.61l-2-1.14a50.15,50.15,0,0,1-19-18.78L2.31,10.1a3.83,3.83,0,0,1,.61-4.61L6.28,2.13h0a1.11,1.11,0,0,1,.78-.33h.06a1.13,1.13,0,0,1,.81.41L12.63,8a1.12,1.12,0,0,1,.24.83l-.65,5.39a2.87,2.87,0,0,0,1,2.56Z"
                                                      fill="#C5C4BE">

                                                </path>
                                            </g>
                                        </g>
                            </svg>
                        </span>
                    {{ com.phone }}
                </a>
                <a href="mailto:{{ com.email }}" class="mail">
                        <span>
                            <svg id="mail-icon" data-name="Ebene 1"
                                 xmlns="http://www.w3.org/2000/svg"
                                 width="33.8" height="27.8"
                                 viewBox="0 0 33.8 27.8">
                            <path id="Path_1573" data-name="Path 1573"
                                  d="M0,27.8H33.8V0H0ZM19.09,13.44a3.11,3.11,0,0,1-4.38,0L3.07,1.8H30.73ZM32,3.07V16.73L25.17,9.9ZM8.63,9.9,1.8,16.73V3.07ZM1.8,26V19.27l8.1-8.1,3.54,3.54a4.91,4.91,0,0,0,6.93,0l3.53-3.54,8.1,8.1V26Z"
                                  fill="#C5C4BE"></path>
                            </svg>
                        </span>
                    {{ com.email }}
                </a>
            </div>
        </div>
        <div class="inner-row bottom-row">
            <div class="social-links">
                <p>بروزباشید.</p>
                <ul>
                    {% for g in social %}
                    <li class="instagram">
                        <a href="https://{{ g.link }}" class="me-3" target="_blank" rel="nofollow">
                            <img src="{{ g.image.url }}" alt="{{ g.title }}" width="34.147" height="34.146">
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="left ps-5">
        <!-- indexer::stop -->
        <nav class="mod_customnav quicklinks block" itemscope="" itemtype="http://schema.org/SiteNavigationElement">
            <a href="en/index.html#skipNavigation10" class="invisible">Skip navigation</a>
            <div class="submenu level_1">
                <ul class="level_1">
                    <li class="first">
                        <a href="{% url 'blog:PostList' %}" title="مقالات" class="first" itemprop="url">
                                <span
                                        class="fnt-size-25 iran" itemprop="name">
                                    مقالات
                                </span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'product:ProductList' %}" title="محصولات"

                           itemprop="url">
                                <span style="font-size: 25px" itemprop="name">
                                    محصولات
                                </span>
                        </a>
                    </li>
                    <li class="unternehmen">
                        <a href="{% url 'project:ProjectList' %}"
                           title="پروژه ها"
                           class="unternehmen" itemprop="url">
                                <span style="font-size: 25px"
                                      itemprop="name">
                                    پروژه ها
                                </span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'catalog:List' %}" title="کاتالوگ ها" itemprop="url">
                                <span style="font-size: 25px"
                                      itemprop="name">
                                        کاتالوگ ها
                                </span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'content:contactus' %}" title="تماس باما" itemprop="url">
                                <span style="font-size: 25px"
                                      itemprop="name">
                                    تماس باما
                                </span>
                        </a>
                    </li>
                    <li class="last">
                        <a href="{% url 'content:about' %}"
                           title="درباره ما" class="last"
                           itemprop="url">
                                <span style="font-size: 25px" itemprop="name">
                                    درباره ما
                                </span>
                        </a>
                    </li>
                </ul>
            </div>
            <a id="skipNavigation10" class="invisible">&nbsp;</a>
        </nav>
        <!-- indexer::continue -->
        <!-- indexer::stop -->
        <nav class="mod_customnav servicelinks block" itemscope=""
             itemtype="http://schema.org/SiteNavigationElement">
            <a href="en/index.html#skipNavigation7" class="invisible">Skip navigation</a>
            <div class="submenu level_1">
                <div class="row">
                    {% for a in licence %}
                        <div class="col-lg-6 col-md-6 col-12 text-center">
                            <img src="{{ a.image.url }}" alt="">
                        </div>
                    {% endfor %}
                </div>
            </div>
            <a id="skipNavigation7" class="invisible">&nbsp;</a>
        </nav>
        <!-- indexer::continue -->
    </div>
</div>

content/templates/partial/logo.html
    <img
            alt="تورک پارکر"
            src="{{ logo.image.url }}"
            class="h-45px h-lg-65px"

    />

content/templates/partial/menu.html
{% for a in object %}
    <li class="{% if a.Child.count != 0 %} submenu {% endif %}sport first"><a
            href="{% url 'product:categoryList' a.slug %}"
            class="submenu sport first"
            aria-haspopup="true" itemprop="url"><span
            itemprop="name">{{ a.title }}</span></a>
        <div class="submenu level_3 ps-20">
            <ul class="level_3">
                {% for b in a.Child.all %}
                    <li class="sport first"><a
                            href="{% url 'product:categoryList' b.slug %}"
                            class="sport first" itemprop="url"><span itemprop="name">{{ b.title }}</span></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </li>
{% endfor %}

content/templates/partial/mobileLogo.html
<div class="d-flex align-items-center flex-grow-1 flex-lg-grow-0">
    <a href="/" class="d-lg-none">
        <img alt="{{ logo.title }}" src="{{ logo.image.url }}" class="h-30px"/>
    </a>
</div>